import { useQuery } from "@tanstack/react-query";
import { api } from "../lib/api";

export interface TemplateItem {
  id: string;
  slug: string;
  title: string;
  category: string;
  categoryLabel: string;
  styleTag: string;
  description: string;
  previewImage: string;
  isPremium?: boolean;
  badgeColor?: string;
  themeColor?: string;
  bgGrad?: string;
  textColor?: string;
  accentColor?: string;
  secondaryAccent?: string;
  fontStyle?: "serif" | "sans";
  layoutVariant?: string;
  price?: number;
}

export function useTemplatesRegistry(category?: string) {
  return useQuery<TemplateItem[]>({
    queryKey: ["templates-registry", category],
    queryFn: async () => {
      const url = category && category !== "all"
        ? `/api/templates?category=${category}`
        : `/api/templates`;

      const res = await api.get<any>(url);
      if (res?.templates && Array.isArray(res.templates) && res.templates.length > 0) {
        return res.templates;
      }
      return ALL_TEMPLATES_FALLBACK;
    },
  });
}

// 47 Master Templates Fallback
export const ALL_TEMPLATES_FALLBACK: TemplateItem[] = [
  {
    id: "480",
    slug: "scroll-scrubber",
    title: "Cinematic 480-Frame Scroll Sequence",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "480-Frame Apple-Style Scroll & Royal Gold",
    description: "Cinematic video image sequence scrubbed smoothly on scroll with black & gold overlay storytelling.",
    previewImage: "/templates/thumbnails/scroll-scrubber.jpg",
    isPremium: true,
    themeColor: "#0B0B0B",
    accentColor: "#D9A441",
  },
  {
    id: "288",
    slug: "premium-scroll",
    title: "Royal Heritage 288-Frame Cinematic Suite",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "288-Frame Royal Emerald & Gold Scroll",
    description: "Exclusive Royal Emerald & Gold 288-frame Apple-style scroll sequence with luxury countdown and venue itinerary.",
    previewImage: "/templates/thumbnails/premium-scroll.jpg",
    isPremium: true,
    themeColor: "#051811",
    accentColor: "#D9A441",
  },
  {
    id: "1",
    slug: "olive-ochre",
    title: "Olive & Ochre Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Earthy Olive & Warm Ochre",
    description: "Mediterranean olive grove aesthetics with warm golden ochre accents, bento events, and editorial typography.",
    previewImage: "/templates/thumbnails/olive-ochre.jpg",
    themeColor: "#556B2F",
    accentColor: "#5f5f00",
  },
  {
    id: "2",
    slug: "modern-minimalist",
    title: "Modern Minimalist Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Deep Amethyst & Champagne Gold",
    description: "High-contrast minimalist luxury layout with glass panel cards, champagne gold accents, and timeline.",
    previewImage: "/templates/thumbnails/modern-minimalist.jpg",
    themeColor: "#31105C",
    accentColor: "#D4AF37",
  },
  {
    id: "3",
    slug: "midnight-noir",
    title: "Midnight Noir Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Obsidian Slate & Platinum",
    description: "Architectural midnight slate backdrop with cool platinum rules, Bodoni typography, and monochromatic photo grid.",
    previewImage: "/templates/thumbnails/midnight-noir.jpg",
    themeColor: "#081425",
    accentColor: "#c1c7cf",
  },
  {
    id: "4",
    slug: "champagne-luxe",
    title: "Champagne Luxe Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Champagne Gold & Soft Parchment",
    description: "Opulent champagne gold aesthetics with frosted glass panels, ambient shadows, and editorial image cards.",
    previewImage: "/templates/thumbnails/champagne-luxe.jpg",
    themeColor: "#735c00",
    accentColor: "#d4af37",
  },
  {
    id: "5",
    slug: "art-deco-revival",
    title: "Art Deco Revival Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "1920s Gatsby Black & Metallic Gold",
    description: "1920s Great Gatsby opulence with double gold hairline borders, rotating diamond emblems, and emerald tints.",
    previewImage: "/templates/thumbnails/art-deco-revival.jpg",
    themeColor: "#131410",
    accentColor: "#d4af37",
  },
  {
    id: "6",
    slug: "classic-floral",
    title: "Classic Floral Wedding",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Blush Roses & Ivory",
    description: "Soft romantic blush pink and ivory cream palette with gold rule accents, couple timeline, and video facade.",
    previewImage: "/templates/thumbnails/classic-floral.jpg",
    themeColor: "#FAF8F5",
    accentColor: "#B85C6B",
  },
  {
    id: "7",
    slug: "seafoam-pearl",
    title: "Seafoam & Pearl Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Seafoam Green & Pearl White",
    description: "Oceanic coastal wedding theme with seafoam green gradients, pearl highlights, and elegant serif typography.",
    previewImage: "/templates/thumbnails/seafoam-pearl.jpg",
    themeColor: "#046c4a",
    accentColor: "#93e9be",
  },
  {
    id: "8",
    slug: "veridian-garden",
    title: "Veridian Garden Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Rich Veridian Green & Floral Gold",
    description: "Deep veridian garden greens with metallic gold flourishes and romantic floral typography.",
    previewImage: "/templates/thumbnails/veridian-garden.jpg",
    themeColor: "#061b0e",
    accentColor: "#735c00",
  },
  {
    id: "9",
    slug: "photo-gallery",
    title: "Photo Gallery Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Editorial Portrait & Modern Grid",
    description: "Minimalist photo-first editorial layout putting couple photography center stage.",
    previewImage: "/templates/thumbnails/photo-gallery.jpg",
    themeColor: "#2b2d42",
    accentColor: "#8d99ae",
  },
  {
    id: "10",
    slug: "whimsical-storybook",
    title: "Whimsical Storybook Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Storybook Tale & Lavender Gold",
    description: "Fairy-tale romance with parchment texture, polaroid photo cards, chapter acts, and lavender mist accents.",
    previewImage: "/templates/thumbnails/whimsical-storybook.jpg",
    themeColor: "#31105C",
    accentColor: "#D4AF37",
  },
  {
    id: "11",
    slug: "grand-ballroom",
    title: "Grand Ballroom Celebration",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Opulent Regal & Formal Black Tie",
    description: "Formal black-tie elegance with grand ballroom background, ornate double hairline glass panels, and mandap imagery.",
    previewImage: "/templates/thumbnails/grand-ballroom.jpg",
    themeColor: "#31105C",
    accentColor: "#D4AF37",
  },
  {
    id: "12",
    slug: "mint-slate",
    title: "Mint & Slate Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Electric Mint & Deep Slate",
    description: "High-contrast editorial layout with electric mint highlights, deep slate typography, and grayscale photo grid.",
    previewImage: "/templates/thumbnails/mint-slate.jpg",
    themeColor: "#246a52",
    accentColor: "#aaf0d1",
  },
  {
    id: "13",
    slug: "jade-ink",
    title: "Jade & Ink Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Deep Emerald Jade & Ink Charcoal",
    description: "Serene zen ink wash aesthetic with deep emerald jade accents, Playfair serif typography, and bento events grid.",
    previewImage: "/templates/thumbnails/jade-ink.jpg",
    themeColor: "#006d43",
    accentColor: "#78fbb6",
  },
  {
    id: "14",
    slug: "lime-silver",
    title: "Lime & Silver Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Electric Lime Neon & Dark Slate",
    description: "High-contrast dark mode cinematic layout with electric lime neon glow accents, kinetic borders, and Oswald display caps.",
    previewImage: "/templates/thumbnails/lime-silver.jpg",
    themeColor: "#32CD32",
    accentColor: "#c6c6c6",
  },
  {
    id: "15",
    slug: "teal-copper",
    title: "Teal & Copper Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Deep Teal Blue & Warm Metallic Copper",
    description: "Glamorous Art Deco vintage layout with deep teal blue-green, warm metallic copper corner borders, and Poiret One display typography.",
    previewImage: "/templates/thumbnails/teal-copper.jpg",
    themeColor: "#008080",
    accentColor: "#ffb77b",
  },
  {
    id: "16",
    slug: "bohemian-sun",
    title: "Bohemian Sun Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Warm Terracotta Rust & Earthy Sage",
    description: "Free-spirited bohemian sun aesthetics with terracotta rust arches, sunburst motifs, and Literata serif typography.",
    previewImage: "/templates/thumbnails/bohemian-sun.jpg",
    themeColor: "#91472a",
    accentColor: "#546347",
  },
  {
    id: "17",
    slug: "emerald-gold",
    title: "Emerald & Gold Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Deep Emerald Green & Metallic Gold",
    description: "Opulent royal emerald green backdrop with metallic gold rules, double-line borders, and Playfair Display serif typography.",
    previewImage: "/templates/thumbnails/emerald-gold.jpg",
    themeColor: "#043927",
    accentColor: "#735c00",
  },
  {
    id: "18",
    slug: "moss-stone",
    title: "Moss & Stone Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Modern Rustic Moss & Warm Stone",
    description: "Modern rustic editorial theme with organic moss green accents, stone wall textures, and Zilla Slab headlines.",
    previewImage: "/templates/thumbnails/moss-stone.jpg",
    themeColor: "#56642b",
    accentColor: "#76786b",
  },
  {
    id: "19",
    slug: "sage-sand",
    title: "Sage & Sand Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Natural Sage Green & Warm Sand Earth",
    description: "Organic rustic wedding theme with natural sage green, warm sand parchment, live countdown grid, and Literata serif typography.",
    previewImage: "/templates/thumbnails/sage-sand.jpg",
    themeColor: "#526442",
    accentColor: "#6c5b4e",
  },
  {
    id: "20",
    slug: "forest-fern",
    title: "Forest & Fern Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Deep Forest Emerald & Botanical Amber",
    description: "Moody botanical dark mode theme with deep forest emerald greens, warm amber accents, fern silhouette overlays, and Literata serif typography.",
    previewImage: "/templates/thumbnails/forest-fern.jpg",
    themeColor: "#13140f",
    accentColor: "#f0bd8b",
  },
  {
    id: "21",
    slug: "botanical-luxe",
    title: "Botanical Luxe Wedding Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Botanical Sage & Rose Gold",
    description: "Signature botanical wedding suite with delicate rose gold foil typography, sage leaf wreaths, and luxury RSVP layout.",
    previewImage: "/templates/thumbnails/botanical-luxe.jpg",
    themeColor: "#526442",
    accentColor: "#b85c6b",
  },
  {
    id: "22",
    slug: "celestial-night",
    title: "Celestial Night & Gold Invitation",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Midnight Navy & Constellation Gold",
    description: "Astronomical night sky wedding suite with golden constellation charts, moon phase countdown, and deep indigo glass panels.",
    previewImage: "/templates/thumbnails/celestial-night.jpg",
    themeColor: "#0a1128",
    accentColor: "#ffd700",
  },
  {
    id: "23",
    slug: "rose-gold-elegance",
    title: "Rose Gold Elegance",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Soft Dusty Rose & Metallic Copper Foil",
    description: "Romantic dusty rose theme with metallic copper foil floral borders, script monogram, and video trailer carousel.",
    previewImage: "/templates/thumbnails/rose-gold-elegance.jpg",
    themeColor: "#f4ebeb",
    accentColor: "#b76e79",
  },
  {
    id: "24",
    slug: "royal-sapphire",
    title: "Royal Sapphire & Diamond",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Deep Royal Sapphire & Platinum",
    description: "Grand imperial Indian royal sapphire wedding theme with ornate gold filigree frames, mandap map, and bento rituals.",
    previewImage: "/templates/thumbnails/royal-sapphire.jpg",
    themeColor: "#0b1d3a",
    accentColor: "#c5a059",
  },
  {
    id: "25",
    slug: "ruby-royale",
    title: "Ruby Royale Wedding Suite",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Imperial Crimson & Gold Brocade",
    description: "Rich traditional crimson red and gold brocade design with auspicious shloka banners, dual partner photos, and Baraat map.",
    previewImage: "/templates/thumbnails/ruby-royale.jpg",
    themeColor: "#4a0404",
    accentColor: "#ffd700",
  },
  {
    id: "26",
    slug: "vintage-newspaper-chronicle",
    title: "The Wedding Chronicle",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Vintage Broadsheet Newspaper Editorial",
    description: "Charming vintage broadsheet newspaper layout with headline articles, couple crossword puzzle, and retro editorial photo columns.",
    previewImage: "/templates/thumbnails/vintage-newspaper-chronicle.jpg",
    themeColor: "#f4f1ea",
    accentColor: "#222222",
  },
  {
    id: "27",
    slug: "japandi-clean-serenity",
    title: "Japandi Serenity",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Zen Wabi-Sabi Wood & Stone",
    description: "Serene minimalist fusion of Japanese aesthetics and Scandinavian functionality with natural linen texture and clean line rules.",
    previewImage: "/templates/thumbnails/japandi-clean-serenity.jpg",
    themeColor: "#e8e5de",
    accentColor: "#5c5549",
  },
  {
    id: "28",
    slug: "space-galaxy-odyssey",
    title: "Cosmic Odyssey",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Deep Space Nebula & Holographic Starlight",
    description: "Futuristic galactic wedding theme with floating stardust particles, neon holographic glows, and orbital planet timeline.",
    previewImage: "/templates/thumbnails/space-galaxy-odyssey.jpg",
    themeColor: "#050510",
    accentColor: "#8a2be2",
  },
  {
    id: "29",
    slug: "storybook-fairytale-wonderland",
    title: "Fairytale Wonderland",
    category: "wedding",
    categoryLabel: "Wedding",
    styleTag: "Illuminated Manuscript & Enchanted Forest",
    description: "Enchanted storybook wedding suite with gilded drop-caps, whimsical woodland flora, and fairytale chapters.",
    previewImage: "/templates/thumbnails/storybook-fairytale-wonderland.jpg",
    themeColor: "#fdfbf7",
    accentColor: "#6b8e23",
  },
  {
    id: "30",
    slug: "tiny-sweet-candy-bash",
    title: "Sweet Pastel Carnival",
    category: "birthday",
    categoryLabel: "Birthday",
    styleTag: "Pastel Macaron & Confetti Sprinkles",
    description: "Playful pastel candy birthday bash with bouncing balloon countdown, cartoon polaroid stickers, and cake cutting schedule.",
    previewImage: "/templates/thumbnails/tiny-sweet-candy-bash.jpg",
    themeColor: "#fff0f5",
    accentColor: "#ff69b4",
  },
  {
    id: "31",
    slug: "cheerful-confetti-carnival",
    title: "Confetti Carnival Fiesta",
    category: "birthday",
    categoryLabel: "Birthday",
    styleTag: "Vibrant Fiesta & Holographic Streamers",
    description: "Ultra-vibrant celebration theme with exploding confetti particles, music playlist widget, and celebratory photo wall.",
    previewImage: "/templates/thumbnails/cheerful-confetti-carnival.jpg",
    themeColor: "#fff8dc",
    accentColor: "#ff4500",
  },
  {
    id: "32",
    slug: "bold-pop-art",
    title: "Retro Pop Art Splash",
    category: "birthday",
    categoryLabel: "Birthday",
    styleTag: "Andy Warhol Halftone & Comic Callouts",
    description: "Energetic 80s pop art theme featuring halftone dots, speech bubbles, neon primary colors, and retro sunglasses sticker peel.",
    previewImage: "/templates/thumbnails/bold-pop-art.jpg",
    themeColor: "#ffeb3b",
    accentColor: "#e91e63",
  },
  {
    id: "33",
    slug: "midnight-monochrome-soiree",
    title: "Monochrome Midnight Soirée",
    category: "birthday",
    categoryLabel: "Birthday",
    styleTag: "Minimalist Black & White High Fashion",
    description: "Vogue-inspired high-fashion editorial birthday invitation with Stark B&W contrast, bold grotesque display types, and guest dress code guide.",
    previewImage: "/templates/thumbnails/midnight-monochrome-soiree.jpg",
    themeColor: "#000000",
    accentColor: "#ffffff",
  },
  {
    id: "34",
    slug: "industrial-loft-soiree",
    title: "Industrial Warehouse Loft",
    category: "birthday",
    categoryLabel: "Birthday",
    styleTag: "Exposed Brick & Edison Filament Amber",
    description: "Chic Brooklyn warehouse party vibes with distressed metal typography, kraft paper tags, and rooftop cocktail itinerary.",
    previewImage: "/templates/thumbnails/industrial-loft-soiree.jpg",
    themeColor: "#2c2a29",
    accentColor: "#d2691e",
  },
  {
    id: "35",
    slug: "roaring-twenties-soiree",
    title: "Roaring 20s Speakeasy",
    category: "birthday",
    categoryLabel: "Birthday",
    styleTag: "Speakeasy Velvet & Champagne Flutes",
    description: "Secret vintage speakeasy birthday party with password entry card, black velvet background, and gold foil cocktails menu.",
    previewImage: "/templates/thumbnails/roaring-twenties-soiree.jpg",
    themeColor: "#111111",
    accentColor: "#d4af37",
  },
  {
    id: "36",
    slug: "pink-champagne-chic",
    title: "Pink Champagne Chic",
    category: "birthday",
    categoryLabel: "Birthday",
    styleTag: "Millennial Pink & Sparkle Gold",
    description: "Glamorous cocktail birthday bash with effervescent champagne bubbles, rose glitter borders, and VIP guestlist.",
    previewImage: "/templates/thumbnails/pink-champagne-chic.jpg",
    themeColor: "#ffe4e1",
    accentColor: "#ff1493",
  },
  {
    id: "37",
    slug: "urban-streetwear-bash",
    title: "Neo-Streetwear Bash",
    category: "birthday",
    categoryLabel: "Birthday",
    styleTag: "Neo-Brutalist Neon Lime & Marquee Hype",
    description: "High-energy neo-brutalist streetwear birthday invitation with marquee scrolling text, barcode badges, and sticker peel archives.",
    previewImage: "/templates/thumbnails/urban-streetwear-bash.jpg",
    themeColor: "#131313",
    accentColor: "#ccff00",
  },
  {
    id: "38",
    slug: "art-deco-grandeur",
    title: "Art Deco Grandeur",
    category: "birthday",
    categoryLabel: "Birthday",
    styleTag: "Burnished Gold & Onyx Sunburst",
    description: "Opulent Roaring Twenties Art Deco birthday invitation featuring burnished gold accents on deep onyx with geometric sunburst patterns.",
    previewImage: "/templates/thumbnails/art-deco-grandeur.jpg",
    themeColor: "#131407",
    accentColor: "#f2ca50",
  },
  {
    id: "39",
    slug: "fresh-citrus-summer",
    title: "Fresh Citrus Summer",
    category: "birthday",
    categoryLabel: "Birthday",
    styleTag: "Radiant Light Cream & Citrus Orange",
    description: "Sun-drenched botanical citrus summer birthday brunch invitation with vibrant orange & leaf green accents and spinning citrus wheels.",
    previewImage: "/templates/thumbnails/fresh-citrus-summer.jpg",
    themeColor: "#fafaf4",
    accentColor: "#ff8c00",
  },
  {
    id: "40",
    slug: "eclectic-chic-masterpiece",
    title: "Eclectic-Chic Masterpiece",
    category: "birthday",
    categoryLabel: "Birthday",
    styleTag: "Warm Beige, Terracotta & Blueprint Grid",
    description: "Artisanal eclectic-chic birthday invitation with warm terracotta accents, blueprint grid textures, and 3-panel comic chapters.",
    previewImage: "/templates/thumbnails/eclectic-chic-masterpiece.jpg",
    themeColor: "#fcf9f8",
    accentColor: "#94492c",
  },
];
